### ISSUE TITLE
Exception without source location when loading Scheme file

### ISSUE THREAD

**Issue by svenha** [marcomaggi/vicare#74]
I am trying to load a large Scheme file, which worked for an older vicare version.
For the current git version, I just see an exception without source location:
vicare -d
Vicare Scheme version 0.4d0, 64-bit
Revision no-branch/no-commit
Build 2015-03-17

Copyright (c) 2006-2010 Abdulaziz Ghuloum and contributors
Copyright (c) 2011-2015 Marco Maggi

vicare> (load "vic.scm")
Exception trapped by debugger.
 Condition components:
   1. &assertion
   2. &who: apply
   3. &message: "incorrect number of arguments"
   4. &irritants: (#<procedure> 5)
[t] Trace. [r] Reraise exception. [c] Continue. [q] Quit. [?] Help. 
vicare>>

How can I get more information (because I have several hundred apply calls)?
Sven

**Comment by marcomaggi** [comment]
Start in debug mode, as you did, them at the debugger prompt hit ```t``` then ```Return```; it should print the stack trace of the offending call.  The debugger is very basic, sorry for this.

**Comment by svenha** [comment]
Thanks, I tried this before and now again:
vicare>> t
CALL FRAMES:
FRAME 0:
 [0] (load "vic.scm")
     operator: #<procedure>
     operands: ("vic.scm")

**Comment by marcomaggi** [comment]
What is the exact screen you see?  For example, if i try to load an unexistent file I get: 

```
vicare> (load "ciao")
Exception trapped by debugger.
 Condition components:
   1. &error
   2. &who: open-file-input-port
   3. &message: "ENOENT: No such file or directory"
   4. &i/o-file-does-not-exist: "ciao"
[t] Trace. [r] Reraise exception. [c] Continue. [q] Quit. [?] Help. 
vicare>> t
CALL FRAMES:
FRAME 0:
 [0] (load "ciao")
     operator: #<procedure>
     operands: ("ciao")
vicare>> 
```

Maybe you have hit an error in the boot image itself.  Is it possible for me to try your source file?

**Comment by marcomaggi** [comment]
I have reduced it to:

```
(define a 1)
(define a 2)
```

where the offending form is the redefinition.  It happens only when evaluating forms in the interaction environment, in which it is possible to redefine bindings.  When we evaluate code at the REPL: definitions go in the interaction environment; when we evaluate code by loading a file with ```load``` with a single argument: definitions go in the interaction environment.  I think I have fixed the problem in the head of the ```master``` branch.

Notice that when importing ```(vicare posix)``` it is, in practise, mandatory to prefix the bindings, otherwise a conflict will arise.  I suggest to do:

```
(import (prefix (vicare posix) px.))
```
